### PR TITLE
Faq feature

### PR DESCRIPTION
**Pull request by samkellerhals**
FAQ section is halfway done now on my end. Please review and merge so I can check everything is working as planned and then I can upload the other half later today.

### CODE REVIEW

**Comment by gndaskalova** [comment]
Hi Sam, do you know why there's a merge conflict? Says the conflict is too complex to resolve in the web editor, and I don't have good enough internet to pull right now. So I suggest you and Izzy continue working on this branch and I will sort out the merge conflict when I'm back to the proper internet tomorrow evening.

**Comment by samkellerhals** [comment]
I am not sure gergana.


Have you had a chance to look at this ?


S

________________________________

**Comment by gndaskalova** [comment]
Will do late tonight most likely!


Gergana Daskalova
PhD student
University of Edinburgh

Website / blog: https://gndaskalova.com/
Coding Club: https://ourcodingclub.github.io/
Twitter: @gndaskalova   @our_codingclub

**Comment by samkellerhals** [comment]
Awesome, let me know!


S

________________________________

**Pull request merged**
