### PR TITLE
Python intro course

### PR DESCRIPTION
**Pull request by dvalters**
This is the Intro to Python course for the tutorial on Wednesday.

The required text/csv file is linked from the tutorial and included in the 'assets' folder (feel free to move it if this is the wrong place for it)

### CODE REVIEW

**Comment by dvalters** [comment]
Updated with the correct jekyll/html syntax now :)

**Comment by johngodlee** [comment]
Hi Declan, 
    I've made a few small changes to the workshop for tomorrow, mostly inconsequential things like typos or linking in our tutorial on Git to access the data.

In the meantime though, there are a few things that I hoped you could address:

* How are students going to construct their scripts? A lot of the code blocks rely on modules that aren't imported in that code block, but it's sometimes unclear whether a student is required to start a new script or amend an existing script, given the new code block they are presented with. Could you do one of the two: either, make it so each code block can be run as a script on its own, which would mean importing modules on each code block, or make it clear when a new script should be started and how a script is to be built up over time. I would suggest making it so that each code block can exist in isolation, and that each code block is an improvement on the previous one.

For example, here is a basic script:

```python
import pandas as pd
data = pd.read_csv('StormEleanor_2_3_Jan.csv', delimiter=',', header=0)
```

Here is an addition to the script to explore the `Pair_Avg` column:

```python
import pandas as pd
data = pd.read_csv('StormEleanor_2_3_Jan.csv', delimiter=',', header=0)

data['Pair_Avg']
```

And finally, here is the way to get the length of the `Pair_Avg` column:

```python
import pandas as pd
data = pd.read_csv('StormEleanor_2_3_Jan.csv', delimiter=',', header=0)

data['Pair_Avg']

len(data['Pair_Avg']
```

* I don't think it's mentioned why we need to create empty list objects before filling them, e.g. `pressure_data = []`, and I don't think it's intuitive, especially for R users, to first create an empty object then fill it later.

* Could you explain briefly the difference between a package and a module, given that you use the words interchangeably.

* Could you explain more thoroughly the workflow for creating a script (even down to what text editors are recommended, e.g. not notepad), then running the script. On a Windows computer especially, "run[ning] it from the command line" isn't simple, and Anaconda doesn't come with a single console, it comes bundled with a few IDE's, the one with the most features being 'spyder'. 
    * For Linux and Mac people it should be easier, presumably once they have installed Anaconda they will also get a Python distribution which they can run from Terminal.app or some other terminal application right?
    * I think if you are asking people to run scripts from the command line it is worth telling them briefly how to navigate to the correct directory using `cd` `ls` etc.

Thanks, and please let me know if you have any questions or don't understand what I'm asking.

I'm thoroughly excited to do this tutorial, I've been teaching myself a bit of python over the last few weeks, the culmination of which is [this poorly written app for downloading podcasts](https://github.com/johngodlee/pypodd).
John

**Comment by dvalters** [comment]
@johngodlee Thanks John - good points. I've made the code blocks 'standalone' (except for one or two where I've clarified I'm just describing the syntax for the first time).

I put a few resources for command line/terminal use (this could easily be a workshop on it's own) and some links to help with installation issues for Windows. I've also mentioned that people can follow along with Spyder if they wish (and are comfortable to do so), as configuring Windows command line to run Python natively can be trickier. (I use linux myself...)

**Comment by johngodlee** [comment]
Hi Declan,
   This all looks great, and thanks for dropping everything and getting it done. I like the fact that you included the SO charts. Yep, I think making the code chunks standalone for the most part makes the whole thing a lot easier. I find it fascinating how the workflow for Python and R differ so much, R is almost always written iteratively, while Python is write a script, amend the script, run the script.

I'll merge this all through tonight before I go to bed and have another quick skim tomorrow morning to catch any snags, it's looking really good though. 

I've got Sam Kellerhals to help us tomorrow in the workshop. He knows a reasonable amount of Python I think, and has helped with workshops before, and I'll be there at about 13:50 to help you get set up.

Thanks again.

**Comment by samkellerhals** [comment]
Hi guys, 
Just went through the tutorial line by line. I've opened a new pull request (fixed some typos), also added a few comments on some bits and bobs worth talking about during the actual tutorial. 
See you tomorrow!

**Pull request merged**
