### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by samkellerhals**
Hi guys great tutorial, well done. 

I've fixed a few typos in the text and one code typo I encountered when running through the script replacing "rb" with "r". 

Just some pointers/thoughts for the tutorial itself, when doing the presentation or maybe just when speaking to people:

-I think it is import to explain to people maybe very shortly in your presentation the concept behind boolean operators. 
-explain that we are working with statements and we are evaluating this statement ( well the python interpreter is for you, these can evaluate to true or false)
-Also maybe state what the “r” parameter stands for reading file, there are also “w” for write and “a” for append, defining modes when calling the open() function.
-also maybe in presentation quickly dissect a basic python statement on screen. Explain what happens in a statement: assigning value to a variable, using function etc. 
-In this line of code maybe expand on the comments:

# Oh no! This is the header line!
print(pressure_data[0])   # Prints: 'Pair_avg'

# Argh! This is a string!
print(type(pressure_data[1])  # Prints: 'str'

Add to comments what we are doing, e.g. printing first value of list, printing second item in list (just to drill in the fact that 0 is first number and 1 is second in python.

-Also add explanation of += operator and <= operator as a comment in the final code block:

while date_time <= date_at_end:
  date_time_series.append(date_time)
  date_time += step

### CODE REVIEW

**Comment by dvalters** [comment]
Thanks @samkellerhals, good finds. I will try to go through things like evaluating statements, functions, booleans etc. slowly on their first appearance. 

Feel free to interject in the workshop if I miss something that might not be obvious to newer users!

**Comment by johngodlee** [comment]
Great stuff Sam, thanks for zipping through the tutorial. Declan I'll wait for you to fix these final few issues then I'll merge this. 

Declan, how do you want to introduce the workshop? Normally we talk for maybe 5 minutes at the most at the start of the workshop to introduce the goals of the session and maybe give some background, this is when you could cover some of the stuff in the intro of your tutorial (why python is great etc.) and the thing Sam suggested about dissecting a couple of simple operations written in python. What do you think?

**Comment by dvalters** [comment]
Hi John, that sounds fine, I will give a brief intro to Python in general and the goals of the session and then go over some of of the first few examples as suggested

**Comment by dvalters** [comment]
Hi John, I don't seem to have permissions to push any changes here. Could you merge it first and I will create a new PR?

**Comment by johngodlee** [comment]
Hi Declan, yer no worries, give me half an hour, I'm changing up the instructions for setting up IDEs and such.

I'll let you know when I've merged

**Pull request merged**
