### PR TITLE
Add 2021 (sem2) team to the website

### PR DESCRIPTION
**Pull request by boyan-kar**

### CODE REVIEW

**Review by EliseGallois — CHANGES_REQUESTED** [review]
Hi Boyan! This all looks great. Just realised I put my bio and pic on the files section of Teams before Lucie made the folder that people have been uploading to. I've now added my bio and pic to there too. Sorry about that! Do you mind adding it in?

**Comment by boyan-kar** [comment]
> 
> 
> Hi @boyan-kar ! This all looks great. Just realised I put my bio and pic on the files section of Teams before Lucie made the folder that people have been uploading to. I've now added my bio and pic to there too. Sorry about that! Do you mind adding it in?

Of course @EliseGallois , sorry I didn't notice it! Will add it right now.

**Comment by boyan-kar** [comment]
I have now added you @EliseGallois

**Review by EliseGallois — APPROVED** [review]
This looks great @boyan-kar! Thanks for all your work on this :)

**Pull request merged**
