### PR TITLE
Boyan tidies up ANOVA tutorial and adds to Tutorials page

### PR DESCRIPTION
**Pull request by boyan-kar**
As discussed in #250

### CODE REVIEW

**Comment by joeschofield0** [comment]
Hi there
I've unsubscribed from this project, but still receiving emails when threads are updated.  Please could an admin remove me from the distribution list?
Many thanks and all best wishes with the project.
Joe

**Comment by EliseGallois** [comment]
> Hi there I've unsubscribed from this project, but still receiving emails when threads are updated. Please could an admin remove me from the distribution list? Many thanks and all best wishes with the project. Joe From: Elise G <notifications@github.com> Sent: 22 February 2021 10:02 To: ourcodingclub/ourcodingclub.github.io <ourcodingclub.github.io@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [ourcodingclub/ourcodingclub.github.io] Boyan tidies up ANOVA tutorial and adds to Tutorials page (#251) CAUTION: This email originated from outside University of Stirling. Do not follow links or open attachments if you doubt the authenticity of the sender or the content.
> […](#)
> ________________________________ Merged #251<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fourcodingclub%2Fourcodingclub.github.io%2Fpull%2F251&data=04%7C01%7Cjoe.schofield%40stir.ac.uk%7Cf011dcd5bae942c39e3608d8d718ea36%7C4e8d09f7cc794ccb9149a4238dd17422%7C0%7C0%7C637495849299658769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=J7ofK0lOymCcbWpRtDOFmAdbdaBsPPNCPuSlfOln1%2BA%3D&reserved=0> into master. - You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fourcodingclub%2Fourcodingclub.github.io%2Fpull%2F251%23event-4358756329&data=04%7C01%7Cjoe.schofield%40stir.ac.uk%7Cf011dcd5bae942c39e3608d8d718ea36%7C4e8d09f7cc794ccb9149a4238dd17422%7C0%7C0%7C637495849299668724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qSOx3ZLftXB0mjmaRKeX%2FC2n0553gEQqflTnHuBom6o%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALLV3U5AMTTJ3XURZKXDOCDTAITRNANCNFSM4X2PJONQ&data=04%7C01%7Cjoe.schofield%40stir.ac.uk%7Cf011dcd5bae942c39e3608d8d718ea36%7C4e8d09f7cc794ccb9149a4238dd17422%7C0%7C0%7C637495849299668724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rmVs1QT2bs7VVosQVfJD8YJrfsI%2BmdyMDQwoUDFhN7U%3D&reserved=0>. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#251 (comment)](https://github.com/ourcodingclub/ourcodingclub.github.io/pull/251#event-4358756329)", "url": "[#251 (comment)](https://github.com/ourcodingclub/ourcodingclub.github.io/pull/251#event-4358756329)", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
> ________________________________ The University achieved an overall 5 stars in the QS World University Rankings 2020 UK Sports University of the Year 2020 (Times Higher Good University Guide) The University of Stirling is a charity registered in Scotland, number SC 011159.

Hi Joe, sorry about that! I'll sort that now. All the best, Elise.

**Comment by joeschofield0** [comment]
👍

**Comment by EliseGallois** [comment]
Hi @joeschofield0! So I went to 'manage access' and actually can't see you listed as a collaborator. You are however listed as 'watching' this repo. Would 'unwatching' us stop these notifications perhaps?

**Comment by joeschofield0** [comment]
Done - hopefully that'll sort it.  Sorry for the inconvenience.
J

**Pull request merged**
