### PR TITLE
Python topic modelling

### PR DESCRIPTION
**Pull request by dfulu**

### CODE REVIEW

**Comment by gndaskalova** [comment]
Just wanted to check @dfulu is this one ready to be merged? Thanks!

**Comment by dfulu** [comment]
Yeh, it's ready

**Comment by dfulu** [comment]
I realise that I probably should have provided a description with this pull request, as that shameful box at the top is reminding me. I'll endeavour to communicate better next time.

**Comment by gndaskalova** [comment]
Hah, that's okay, no worries!

**Comment by gndaskalova** [comment]
The tweet/Python logo is lovely!

**Comment by dfulu** [comment]
Thanks 😸

**Pull request merged**
