### PR TITLE
Beverly added herself to the team

### PR DESCRIPTION
**Pull request by beverlytan**

### CODE REVIEW

**Comment by beverlytan** [comment]
Hey @gndaskalova i just tried to upload an image to the team page, but I think my rights to upload images to the "img" folder have somehow been lost?? This is the error message I receive: "Uploads are disabled. File uploads require push access to this repository."

I'm not sure why this is the case because previously I was able to add images to this folder!

**Comment by gndaskalova** [comment]
@beverlytan can you upload the photo in a pull request? I wonder what happened. Maybe something with github changed, cause I haven't changed your right or anything, and you were able to upload images before... If you can't upload images in a pull request either, I'll have a more thorough look into what has happened!

**Comment by beverlytan** [comment]
No I can't, at least I don't think it will add it to the folder I think it will just attach to the comment itself! Yeah I think there must have been some sort of update because that would have been the only way I added photos. @gndaskalova

**Comment by gndaskalova** [comment]
Can you try now? I just gave writing privileges to all members of the CC organisation.

**Comment by beverlytan** [comment]
OK its back!! 

image

This is what its showing, which is the same as before this happened so yes I can make pull requests (and enter the upload image screen) but not commit to the branch directly. 

Thank you :-)

**Pull request merged**
